### ISSUE TITLE
[Proposal] Windows-Specific Popup Border Color

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#102]
# WindowsPopupBorderColor

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

A windows-specific control to change the border color of a `Popup`.

## Detailed Design
[design]: #detailed-design

### Popup.shared.cs

```cs
using Xamarin.CommunityToolkit.UI.Views;
using Xamarin.Forms;
using XCTElement = Xamarin.CommunityToolkit.UI.Views.BasePopup;
using XFPC = Xamarin.Forms.PlatformConfiguration;

namespace Xamarin.CommunityToolkit.PlatformConfiguration.WindowsSpecific
{
	public static class PopUp
	{
		public static readonly BindableProperty BorderColorProperty = BindableProperty.Create(
			"BorderColor", typeof(Color), typeof(BasePopup), default(Color));

		public static void SetBorderColor(BindableObject element, Color color) =>
			element.SetValue(BorderColorProperty, color);

		public static Color GetBorderColor(BindableObject element) =>
			(Color)element.GetValue(BorderColorProperty);

		public static IPlatformElementConfiguration<XFPC.Windows, XCTElement> SetBorderColor(this IPlatformElementConfiguration<XFPC.Windows, XCTElement> config, Color value)
		{
			SetBorderColor(config.Element, value);
			return config;
		}
	}
}
```

## Usage Syntax
[usage]: #usage-syntax

<!-- Here is an example from CharactersValidationBehavior:

### XAML Usage

```xml
<Popup windows:Popup.BorderColor="Black" />
```

### C# Usage

```cs
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.WindowsSpecific;
...

var popup = new Popup();
popup.On<Windows>().SetBorderColor(Colors.Black);
```
```[tasklist]
### Tasks
```

**Comment by mouralabank** [comment]
Any updates?

**Comment by stbau04** [comment]
Is there still help wanted on this one? If so, i'd be down to help out

**Comment by brminnick** [comment]
@pictos- It looks like you're the Champion for this Proposal. Would you like to assign it to @stbau04?

**Comment by pictos** [comment]
@brminnick I think it's good to block this issue until we merge #1086, since the Popup implementation will change

**Comment by vhugogarcia** [comment]
@brminnick can we go ahead and close this issue since the PR [#1086](https://github.com/CommunityToolkit/Maui/pull/1086) has been merged? 😃

**Comment by brminnick** [comment]
I've removed the `blocked` label. 

@stbau04 - could you confirm this feature is still necessary? If so, we can assign it to you.

**Comment by pictos** [comment]
Friendly reminder we changed the Windows implementation to use another platform specific control, with that we need to check if the new control allows this customization.

Do you know something about it @VladislavAntonyuk ?

**Comment by VladislavAntonyuk** [comment]
Windows samples use Border inside Popup control (see example https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.popup?view=winrt-22621)

**Comment by pictos** [comment]
So there's no way to change the border of the popup, we need to wrap the layout to a border, if that's true we can close this issue

**Comment by vhugogarcia** [comment]
> So there's no way to change the border of the popup, we need to wrap the layout to a border, if that's true we can close this issue
> 
> 

That is what I understood as well.

**Comment by vhugogarcia** [comment]
Per the discussion above. I'm closing this issue. We can re-open it if necessary.
