### ISSUE TITLE
MediaElement TODO list

### ISSUE THREAD

**Issue by jfversluis** [CommunityToolkit/Maui#717]
Just putting this issue out here with some things we might want to look into regarding MediaElement without littering the repo with issues for a control that doesn't exist yet.

If you are reading this as a "outside" user, feel free to add any feedback as comments under this issue while MediaElement is still being implemented.

* [x] Got [this repo](https://github.com/Varmod/LocalVideoWontPlay) through someone on my blogpost, just pointing to a filename doesn't work. TODO: Check if we support this scenario and why it doesn't work or how we can easily accommodate this scenario.

Implemented the ResourceMediaSource for loading local media. We might need to make the detection smarter if the users adds a URL or filename in there though, but at least it should be possible to play this easily now

* [x] Fix iOS 16 platform playback control stuff; somewhat done, it shows, but there is a weird top offset thing going on, possibly a bug in .NET MAUI
* [x] Implement MediaManager (underway by @pictos)
* [x] See why [this link](https://mintbackend.azurewebsites.net/api/getuploads/RDpcaG9tZVxzaXRlXHd3d3Jvb3RcdXBsb2Fkc1xjY2dsbHMyZS5qNWEubXA0/dmlkZW8vbXA0) isn’t working on iOS **
* [x] See why [this link](https://samcloud.spacial.com/api/listen?sid=73841&rid=259088&f=mp3,any&br=128000,any&m=sc&t=ssl) isn't working on Android. Has to do with no duration being reported and that overflowing the TimeSpan we try to set for the duration. We need to account for that. Fixed with #787 
* [x] Why is this happening on Android: https://github.com/CommunityToolkit/Maui/issues/113#issuecomment-1303161996
* [x] Make the status (playing, paused, etc.) consistent

** This link doesn't work and fails with this error on iOS
> LocalizedFailureReason: "The server is not correctly configured."
	LocalizedRecoveryOptions: (null)
	LocalizedRecoverySuggestion: (null)
	UnderlyingErrors: {Foundation.NSError[1]}
	UserInfo: {{
    NSLocalizedDescription = "Operation Stopped";
    NSLocalizedFailureReason = "The server is not correctly configured.";
    NSUnderlyingError = "Error Domain=CoreMediaErrorDomain Code=-12939 \"byte range length mismatch - should be length 2 is length 189217134\" UserInfo={NSDescription=byte range length mismatch - should be length 2 is length 189217134, NSURL=https://mintbackend.azurewebsites.net/api/getuploads/RDpcaG9tZVxzaXRlXHd3d3Jvb3RcdXBsb2Fkc1xjY2dsbHMyZS5qNWEubXA0/dmlkZW8vbXA0}";

It seems that this is simply something that is incompatible with iOS and required extra configuration on the server-side.

* [x] Add ILogger messages where useful
* [x] Make SeekComplete work on iOS for scrubbing with platform control (already works with seeking through custom control)
* [x] Make SeekComplete not fire multiple times on Android when using a custom control (already works when using platform control)
* [x] Implement MediaEnded on Windows
* [x] Add KeepScreenOn
* [x] Investigate if we can implement KeepScreenOn for Windows
* [x] Double-check/fix the TODOs in code
* [x] Check if volume/speed/etc. is in sync between platform player controls and our own when setting it through MediaElement or vice versa

**Comment by plattski** [comment]
Where is the MediaElement package as of right now? Can't seem to find it anywhere. Tx

**Comment by jfversluis** [comment]
Please see this blog post on how to use it today: https://blog.verslu.is/maui/mediaelement-for-net-maui-early-preview/

Please keep in mind that it’s under active development. Things are not complete, bugged or might change before it gets released.

**Comment by iascience** [comment]
For audio on Android, will this create a player in notification manager, so audio continues to play in the background and can be controlled from the lock screen? I know the XamarinMediaManager package has had problems with this in Android 12.

**Comment by HausBJB** [comment]
Hello @jfversluis,

Have you ever thought about Silent Mode? When silent mode is activated on an iPhone, no audio is allowed to play, right?

**Comment by bijington** [comment]
> Hello @jfversluis,
> 
> 
> 
> Have you ever thought about Silent Mode? When silent mode is activated on an iPhone, no audio is allowed to play, right?

Users can still control audio volume even in silent mode. My phone is always on silent but videos can still play audio

**Comment by mhrastegari** [comment]
Can we have TapGestureRecognizer on Android? Works fine on WinUI but on Android it only works when i set ShowsPlaybackControls to false.

**Comment by sturlath** [comment]
What about streaming with EAS and DRM, is that on the radar?

**Comment by jfversluis** [comment]
I don't know what EAS is, and DRM is definitely requested and on my radar, not sure if that will be part of v1.

**Comment by sturlath** [comment]
AES is token encryption for the stream and for Safari iOS you need to jump through hoops to make it work so I thought to ask. But like that you are looking into DRM!

See more on DRM and AES here https://learn.microsoft.com/en-us/azure/media-services/latest/drm-content-protection-concept

**Comment by jfversluis** [comment]
Of course if you have any pre-existing knowledge here that we can apply, feel free to contribute whenever we have merged our first version :)

**Comment by scottkuhl** [comment]
How about adding support for AirPlay, Chromecast and MiraCast baked right into the control?

**Comment by brminnick** [comment]
Hi @scottkuhl! The Proposal for MediaElement has been voted on and approved in its [New Feature Proposal](https://github.com/CommunityToolkit/Maui/issues/113#issuecomment-1303161996).

To propose a new feature or API, I recommend [opening a new Discussion](https://github.com/communitytoolkit/maui/discussions/new). In our workflow, all new features start as a [new Discussion](https://github.com/communitytoolkit/maui/discussions/new); you can learn more into our workflow [here](https://github.com/CommunityToolkit/Maui/blob/main/README.md#submitting-a-new-feature) in the README: https://github.com/CommunityToolkit/Maui/blob/main/README.md#submitting-a-new-feature.

**Comment by scottkuhl** [comment]
@brminnick I thought that was what this issue was specifically for, to discuss features we want to see in this control.  I'm happy to start a discussion, but I don't understand the purpose of this issue then.

See the OP:

_Just putting this issue out here with some things we might want to look into regarding MediaElement without littering the repo with issues for a control that doesn't exist yet._

_If you are reading this as a "outside" user, feel free to add any feedback as comments under this issue while MediaElement is still being implemented._

**Comment by brminnick** [comment]
Apologies! I'm the one who is lost. I mistakenly thought this was the PR for MediaElement.

**Comment by ross8alex** [comment]
Getting "Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view CommunityToolkit.Maui.MediaElement.MediaElement.'" when trying to use the latest version on Nuget - on android, haven't tested on iOS, seems to happen with images, gifs, and videos. I haven't seen anyone talking about this, is there something I could have done wrong?

**Comment by pictos** [comment]
@ross8alex can you create a github repo with your project and share the link with us?

**Comment by ross8alex** [comment]
@pictos I've created a new test project to demonstrate the issue here: [](https://github.com/ross8alex/MediaElementTestApp/)

**Comment by pictos** [comment]
@ross8alex you need to call the `UseMauiCommunityToolkitMediaElement` [here](https://github.com/ross8alex/MediaElementTestApp/blob/main/MediaElementTestApp/MediaElementTestApp/MauiProgram.cs)

```csharp
var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.UseMauiCommunityToolkitMediaElement()
            .ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});
```

**Comment by ross8alex** [comment]
@pictos thanks, that worked beautifully! I'd recommend to @jfversluis to make a minor addition to the [MediaElement blog post](https://blog.verslu.is/maui/mediaelement-for-net-maui-early-preview/) for people like me who hadn't used the toolkit before and didn't realize initializing it in the MauiProgram file was necessary.

**Comment by jfversluis** [comment]
OK I think I fixed all on this list, closing this for now!
